# Base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to work directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files to work directory
COPY . .

# Build the app
RUN npm run build

# Set environment variables
ENV PORT=3000

# Expose port
EXPOSE $PORT

# Start the app
CMD ["npm", "run", "start"]